spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b08e2b651985f2440b7f
            clientSecret: 891acf5785a5af14ebe4827c0d9606b3385304cd

logging:
  level:
    root: error
    org.springframework.security: DEBUG